### ISSUE TITLE
make a issues

### ISSUE THREAD

**Issue by Clin-git** [Soway-code/Code-review#24]
no context

**Comment by Soway-code** [comment]
hei U are on line!! 
| |
陆道逸
|
|
loodao@163.com
|
签名由网易邮箱大师定制
On 4/3/2020 09:56，Clin-git<notifications@github.com> wrote：

no context

**Comment by Soway-code** [comment]
issues passed

**Comment by Soway-code** [comment]
@Clin-git 我还用我邮箱回复了你，你查下你的邮箱是否有收到？

**Comment by Clin-git** [comment]
收到了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"loodao"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月3日(星期五) 上午10:04
收件人:&nbsp;"Soway-code/Code-review"<Code-review@noreply.github.com&gt;;
抄送:&nbsp;"clink"<371921187@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Soway-code/Code-review] make a issues (#24)





 
@Clin-git 我还用我邮箱回复了你，你查下你的邮箱是否有收到？

**Comment by Soway-code** [comment]
closed it
