### ISSUE TITLE
hei guy  about the CI building for gitee

### ISSUE THREAD

**Issue by hunkhand** [Soway-code/Code-review#4]
the way build CI for gitee --->  jenkins some more pugin will help make it !!

**Comment by loodao** [comment]
THs !! emmm!!!

**Comment by hunkhand** [comment]
i just get the message of SYN with gitee !! great ,big guy

**Comment by loodao** [comment]
Yes! PLS to check !!

**Comment by hunkhand** [comment]
#include <stdio.h>
int main()
{
    puts("how big the world as u mind!!");
   return (0);
}

**Comment by loodao** [comment]
PLC PR the emmbedded code to try CI setting param; maybe some one false,, ahah

**Comment by loodao** [comment]
@hunkhand  up issue

**Comment by Soway-code** [comment]
all guys Builded more new subjects & split code review , training and will add be future TKS

**Comment by Soway-code** [comment]
@hunkhand

**Comment by Soway-code** [comment]
closed it
